
title: Arjun Lakhanpal
logo: /arjun1.jpg # Reference the image directly from the root folder
description: AI/ML Engineer
Location: India, New Delhi
theme: jekyll-theme-minimal

# GitHub Pages configuration
baseurl: "/arjunlakhanpal.io"
url: "https://arjunlakhanpall.github.io"

# Build settings
markdown: kramdown
highlighter: rouge 
