title: Arjun Lakhanpal
theme: jekyll-theme-minimal

description: >
  <a href="mailto:lakhanpxl.arjun@gmail.com">✉️ Email</a> |
  <a href="https://www.linkedin.com/in/arjunlakhanpall/">👔 LinkedIn</a> |
  <a href="https://github.com/Arjunlakhanpall">💻 GitHub</a>
