title: Arjun Lakhanpal
logo: /assets/images/arjun.png
description: AIML Engineer

theme: jekyll-theme-minimal

# Social links
github: https://github.com/Arjunlakhanpall
linkedin: https://www.linkedin.com/in/arjunlakhanpall/
website: https://arjunlakhanpall.github.io/arjunlakhanpal.io/


