title: Arjun Lakhanpal
logo: /arjun.png  # Reference the image directly from the root folder
description: AI/ML Engineer

github: Arjunlakhanpall
linkedin: arjunlakhanpall
website: arjunlakhanpall.github.io/arjunlakhanpal.io

location:
  country: India
  state: Delhi
  city: New Delhi
  time_zone: 13:59 (UTC +05:30)

about_me: https://about.me/arjunlakhanpall
linkedin_profile: https://www.linkedin.com/in/arjunlakhanpall/


theme: jekyll-theme-minimal
